egrep -i postgres ./run.py
egrep -i postgres ./test_complete_schema.py
egrep -i postgres ./app/database/__init__.py
egrep -i postgres ./app/database/connection.py
egrep -i postgres ./app/auth/__init__.py
egrep -i postgres ./app/auth/dependencies.py
egrep -i postgres ./app/auth/jwt.py
egrep -i postgres ./app/__init__.py
egrep -i postgres ./app/models/user.py
egrep -i postgres ./app/models/follow.py
egrep -i postgres ./app/models/holding.py
egrep -i postgres ./app/models/__init__.py
egrep -i postgres ./app/models/historical_performance.py
egrep -i postgres ./app/models/portfolio.py
egrep -i postgres ./app/schemas/auth.py
egrep -i postgres ./app/schemas/__init__.py
egrep -i postgres ./app/schemas/portfolio.py
egrep -i postgres ./app/main.py
egrep -i postgres ./app/routes/auth.py
egrep -i postgres ./app/routes/__init__.py
egrep -i postgres ./app/routes/portfolio.py
egrep -i postgres ./app/services/__init__.py
egrep -i postgres ./app/services/portfolio_service.py
egrep -i postgres ./test_startup.py
egrep -i postgres ./test_authentication.py
egrep -i postgres ./test_database_models.py
egrep -i postgres ./test_db_connection.py
egrep -i postgres ./check_database.py
egrep -i postgres ./alembic/env.py
egrep -i postgres ./alembic/versions/ecf4c4978b97_create_portfolios_holdings_historical_.py
egrep -i postgres ./alembic/versions/a6e3b1ad8ac5_create_users_table.py
egrep -i postgres ./test_portfolio_system.py
