"""Add adjusted_close column to asset_prices

Revision ID: 0f660e205a17
Revises: 7d8fea640df6
Create Date: 2025-07-14 14:31:12.218627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f660e205a17'
down_revision: Union[str, None] = '7d8fea640df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_prices', sa.Column('adjusted_close', sa.Float(), nullable=False))
    op.alter_column('asset_prices', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('asset_prices', 'open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_prices', 'high_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_prices', 'low_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('asset_prices', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('unique_symbol_date', 'asset_prices', type_='unique')
    op.drop_column('asset_prices', 'data_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_prices', sa.Column('data_source', sa.VARCHAR(), server_default=sa.text("'financialmodelingprep'::character varying"), autoincrement=False, nullable=True))
    op.create_unique_constraint('unique_symbol_date', 'asset_prices', ['symbol', 'date'])
    op.alter_column('asset_prices', 'volume',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('asset_prices', 'low_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('asset_prices', 'high_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('asset_prices', 'open_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('asset_prices', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('asset_prices', 'adjusted_close')
    # ### end Alembic commands ###
