"""Create portfolios, holdings, historical_performance, and follows tables

Revision ID: ecf4c4978b97
Revises: a6e3b1ad8ac5
Create Date: 2025-07-07 10:40:09.069854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf4c4978b97'
down_revision: Union[str, None] = 'a6e3b1ad8ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_model_portfolio', sa.Boolean(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('total_cost_basis', sa.Float(), nullable=True),
    sa.Column('total_return_amount', sa.Float(), nullable=True),
    sa.Column('total_return_percentage', sa.Float(), nullable=True),
    sa.Column('daily_return_amount', sa.Float(), nullable=True),
    sa.Column('daily_return_percentage', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_calculated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'portfolio_id', name='_follower_portfolio_uc')
    )
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_table('historical_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_cost_basis', sa.Float(), nullable=False),
    sa.Column('total_return_amount', sa.Float(), nullable=False),
    sa.Column('total_return_percentage', sa.Float(), nullable=False),
    sa.Column('daily_return_amount', sa.Float(), nullable=True),
    sa.Column('daily_return_percentage', sa.Float(), nullable=True),
    sa.Column('volatility_30d', sa.Float(), nullable=True),
    sa.Column('sp500_return', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date', name='_portfolio_date_uc')
    )
    op.create_index(op.f('ix_historical_performance_date'), 'historical_performance', ['date'], unique=False)
    op.create_index(op.f('ix_historical_performance_id'), 'historical_performance', ['id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'ETF', 'OPTION', 'CRYPTO', 'COMMODITY', 'BOND', name='assettype'), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('total_cost_basis', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unrealized_gain_loss', sa.Float(), nullable=True),
    sa.Column('unrealized_return_percentage', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_price_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_historical_performance_id'), table_name='historical_performance')
    op.drop_index(op.f('ix_historical_performance_date'), table_name='historical_performance')
    op.drop_table('historical_performance')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
